name: Deploy static site to public repo
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run build
      # publish "dist" to another repo (Repo B)
      - name: Deploy to public pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          external_repository: doonops/doonops.github.io   # <-- Repo B
          publish_branch: main                              # or gh-pages
          cname: doonops.com                                # CNAME file auto
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}       # repo deploy key
